name: bindplane
services:
  transform:
    image: ghcr.io/observiq/bindplane-transform-agent:latest
    ports:
      - "4568:4568"
    networks:
      - bindplane-network
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=bindplane
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-bindplane}
      - POSTGRES_DB=bindplane
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bindplane"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - bindplane-network
  prometheus:
    image: prom/prometheus:v2.55.0
    ports:
      - "9010:9090"
    command:
      - '--web.enable-remote-write-receiver'
      - '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/rules.yml:/etc/prometheus/rules.yml
    networks:
      - bindplane-network
  bindplane:
    image: ghcr.io/observiq/bindplane-ee:${GIT_SHA}
    ports:
      - "3010:3001"
    environment:
      - BINDPLANE_REMOTE_URL=http://localhost:3010
      - BINDPLANE_SESSIONS_SECRET=${BINDPLANE_SESSIONS_SECRET}
      - BINDPLANE_LOG_OUTPUT=stdout
      - BINDPLANE_SECRET_KEY=${BINDPLANE_SECRET_KEY}
      - BINDPLANE_TRANSFORM_AGENT_ENABLE_REMOTE=true
      - BINDPLANE_TRANSFORM_AGENT_REMOTE_AGENTS=transform:4568
      - BINDPLANE_PROMETHEUS_ENABLE_REMOTE=true
      - BINDPLANE_PROMETHEUS_HOST=prometheus
      - BINDPLANE_PROMETHEUS_PORT=9090
      # - BINDPLANE_ANALYTICS_DISABLED=true
      - BINDPLANE_LICENSE=${BINDPLANE_LICENSE}
    depends_on:
      postgres:
        condition: service_healthy
      transform:
        condition: service_started
      prometheus:
        condition: service_started
    networks:
      - bindplane-network

networks:
  bindplane-network:
    driver: bridge

volumes:
  postgres-data:
