name: Docker Compose Validation

on:
  push:
    branches: [main]
    paths:
      - "docker-compose/**"
      - ".github/workflows/docker-validate.yml"
  pull_request:
    branches: [main]
    paths:
      - "docker-compose/**"
      - ".github/workflows/docker-validate.yml"

jobs:
  docker-validate:
    name: Docker Compose Validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Set up Docker Compose explicitly
      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose-plugin
          docker compose version

      - name: Docker Compose Validation
        run: |
          cd docker-compose
          docker compose config -q

      # Run Hadolint directly without SARIF output
      - name: Lint Dockerfiles
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: docker-compose/Dockerfile*
          failure-threshold: error

      # Alternative approach using direct Hadolint installation
      - name: Install Hadolint
        run: |
          wget -q https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64
          chmod +x hadolint-Linux-x86_64
          sudo mv hadolint-Linux-x86_64 /usr/local/bin/hadolint

      - name: Run Hadolint manually
        run: |
          if [ -d "docker-compose" ] && [ -n "$(find docker-compose -name 'Dockerfile*' -print -quit)" ]; then
            find docker-compose -name 'Dockerfile*' -exec hadolint {} \;
          else
            echo "No Dockerfiles found to lint"
          fi
