name: Security Scan

on:
  push:
    branches: [main]
    paths:
      - "terraform/**"
      - "docker-compose/**"
      - ".github/workflows/security-scan.yml"
  pull_request:
    branches: [main]
    paths:
      - "terraform/**"
      - "docker-compose/**"
      - ".github/workflows/security-scan.yml"
  schedule:
    - cron: "0 0 * * 0" # Run weekly on Sunday at midnight

jobs:
  terraform-security:
    name: Terraform Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run TFSec
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          working_directory: terraform

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: terraform
          framework: terraform
          quiet: true
          skip_check: CKV_AWS_* # Skip AWS checks if you're only using GCP

  docker-security:
    name: Docker Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Check existing Docker and Docker Compose
      - name: Check Docker setup
        run: |
          docker --version
          docker compose version || echo "Compose plugin not available"
          which docker-compose || echo "Standalone docker-compose not found"

      # Install Docker Compose V2 as a plugin (most reliable method)
      - name: Install Docker Compose V2
        run: |
          DOCKER_COMPOSE_VERSION=v2.24.6
          mkdir -p ~/.docker/cli-plugins/
          curl -SL "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-linux-x86_64" -o ~/.docker/cli-plugins/docker-compose
          chmod +x ~/.docker/cli-plugins/docker-compose
          docker compose version

      - name: Docker Compose Validation
        run: |
          cd docker-compose
          docker compose config -q

      - name: Run Trivy Config Scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "config"
          scan-ref: "docker-compose"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          severity: "CRITICAL,HIGH"
