name: Security Scan

on:
  push:
    branches: [main]
    paths:
      - "terraform/**"
      - "docker-compose/**"
      - ".github/workflows/security-scan.yml"
  pull_request:
    branches: [main]
    paths:
      - "terraform/**"
      - "docker-compose/**"
      - ".github/workflows/security-scan.yml"
  schedule:
    - cron: "0 0 * * 0" # Run weekly on Sunday at midnight

jobs:
  terraform-security:
    name: Terraform Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run TFSec
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          working_directory: terraform

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: terraform
          framework: terraform
          quiet: true
          skip_check: CKV_AWS_* # Skip AWS checks if you're only using GCP

  docker-security:
    name: Docker Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker Compose Validation
        run: |
          cd docker-compose
          docker-compose config -q

      - name: Run Trivy Config Scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "config"
          scan-ref: "docker-compose"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          severity: "CRITICAL,HIGH"
